# Указываем стабильный образ Python 3.11
FROM python:3.11-slim

# Создаем рабочую директорию
WORKDIR /app

# Копируем проект и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальное
COPY . .

# Запуск бота
CMD ["python", "main.py"]